name: PlatinumMMO
main: com.gmail.Annarkwin.Platinum.MMO.MMO
version: 1.0
api-version: 1.16
depend: [PlatinumAPI]

commands:
  AFK:
    description: "Set your AFK Status"
    aliases: []
    permission: platinum.command.afk
    usage: /AFK Help
  Enderchest:
    description: "Administrate enderchests"
    aliases: [ec]
    permission: platinum.command.enderchest
    usage: /Enderchest Help
  Inventory:
    description: "Administrate inventories"
    aliases: [inv]
    permission: platinum.command.inventory
    usage: /Inventory Help
  Test:
    description: "Test Command"
    aliases: []
    permission: platinum.command.test
    usage: /Test
  Portal:
    description: "Hook portals to warp points for public use"
    aliases: []
    permission: platinum.command.portal
    usage: /Portal Help
  Quarry:
    description: "Make automatically regenerating quarries"
    aliases: []
    permission: platinum.command.quarry
    usage: /Quarry Help
  Region:
    description: "Set up protected regions"
    aliases: [rg]
    permission: platinum.command.region
    usage: /Region Help
  Spawn:
    description: "Alias for /warp go spawn"
    aliases: []
    permission: platinum.command.spawn
    usage: /Spawn Help
  Sudo:
    description: "Force someone to run a command"
    aliases: []
    permission: platinum.command.sudo
    usage: /Sudo Help
  Warp:
    description: "Create warp points for fast travel"
    aliases: []
    permission: platinum.command.warp
    usage: /Warp Help

permissions:
  platinum.afk.user:
    default: true
    children:
      platinum.command.afk: true
      platinum.command.afk.help: true
      platinum.command.afk.afk: true
  platinum.quarry.user:
    default: true
    children:
      platinum.command.quarry: true
      platinum.command.quarry.help: true
      platinum.command.quarry.list: true
  platinum.warp.user:
    default: true
    children:
      platinum.command.warp: true
      platinum.command.warp.help: true
      platinum.command.warp.go: true
      platinum.command.warp.list: true
  platinum.region.user:
    default: true
    children:
      platinum.command.region: true
      platinum.command.region.help: true
      platinum.command.region.info: true
      platinum.command.region.allowed: true
      platinum.command.region.allow: true
      platinum.command.region.kick: true
  platinum.spawn.user:
    default: true
    children:
      platinum.command.warp: true
      platinum.command.warp.go: true
      platinum.command.spawn: true
      platinum.command.spawn.help: true
  platinum.inventory.user:
    default: true
    children:
      platinum.command.inventory: true
      platinum.command.inventory.help: true
      platinum.command.inventory.drop: true